[theme]
# Cor principal de destaque (Botões, Links, Checkboxes)
primaryColor = "#4A90E2"

# Cor de fundo da área de conteúdo principal
backgroundColor = "#dadada"

# Cor de fundo da barra lateral (Sidebar)
secondaryBackgroundColor = "#E8ECEF"

# Cor do texto principal
textColor = "#2C3E50"

# Fonte do sistema (mais limpa e corporativa)
font = "sans serif"

[client]
# Remove o menu de opções do canto superior direito e o rodapé "Made with Streamlit"
toolbarMode = "minimal"
showErrorDetails = true

[browser]
# Remove o botão de "Stop/Rerun" que aparece no topo para o usuário final
gatherUsageStats = false