import { GlassCard } from '../components/Layout/GlassCard';
import { useDashboardData } from '../context/useDashboardData';
import { useTheme } from '../context/useTheme';

export function Investigations() {
  const { investigations, loading } = useDashboardData();
  const { theme } = useTheme();
  const formatCurrency = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
  return <section className="pointer-events-auto min-h-full p-6 md:p-8"><header className="mb-6"><div className="text-xs font-black tracking-[0.25em] text-white uppercase">Investigations</div><div className="mt-1 text-[9px] tracking-widest text-slate-500 uppercase">Ranking priorizado por risco e exposição financeira</div></header><GlassCard className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-white/5 bg-white/[0.03] px-5 py-4"><span className="text-[10px] font-black tracking-widest text-white uppercase">Fila de investigação</span><span className="text-[9px] text-slate-500">{loading ? 'Sincronizando…' : `${investigations.length} casos`}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="border-b border-white/5 text-[9px] tracking-widest text-slate-500 uppercase"><tr>{['Rank','Proposta','Local','Resultado','Risco','Exposição'].map((head) => <th key={head} className="px-5 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-white/[0.035]">{investigations.map((item, index) => <tr key={item.id} className="transition-colors hover:bg-white/[0.035]"><td className="px-5 py-4 font-mono text-xs text-slate-500">#{String(index + 1).padStart(2,'0')}</td><td className="px-5 py-4"><div className="text-xs font-bold text-white">PR-{item.id}</div><div className="text-[9px] text-slate-500">{item.cliente}</div></td><td className="px-5 py-4 text-[10px] text-slate-300">{item.municipio} · {item.uf}</td><td className="px-5 py-4"><span className="rounded border px-2 py-1 text-[9px] font-black" style={{ color: theme.primary, borderColor: `${theme.primary}55`, background: `${theme.primary}12` }}>{item.status}</span></td><td className="px-5 py-4"><div className="font-black text-white">{item.risco_score}</div><div className="mt-1 h-1 w-20 rounded bg-white/10"><div className="h-full rounded" style={{ width: `${item.risco_score}%`, background: theme.primary }} /></div></td><td className="px-5 py-4 text-xs font-black text-white">{formatCurrency(item.valor)}</td></tr>)}</tbody></table></div></GlassCard></section>;
}
